allprojects {
    repositories {
        maven {
            url 'http://192.168.1.110:6001/repository/maven-releases/'
            allowInsecureProtocol = true
        }
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
